package com.example.quantumsimulator.DataModels

data class QuantumChapter(val title: String, val discription: String, val explanation: String, val imageUrl: String, var isExpanded: Boolean = false)

val chapterList = listOf(
    QuantumChapter("Introduction to Quantum Physics", "Basics of quantum theory, its necessity, and the failure of classical physics.", "Quantum physics explores the behavior of matter and energy at the atomic and subatomic levels. It emerged in the early 20th century to address phenomena unexplained by classical physics, such as blackbody radiation and the photoelectric effect. Max Planck introduced the idea that energy is quantized, leading to the development of quantum theory." ,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3_krklsrQZTsmTFcc5uV_WjlkB8H2SeprUw&s"),
    QuantumChapter("Wave-Particle Duality", "Understanding how particles like electrons and photons exhibit both wave-like and particle-like properties.","Wave-particle duality is a fundamental concept in quantum mechanics, demonstrating that particles can display characteristics of both waves and particles. The double-slit experiment reveals that electrons can produce interference patterns, a property of waves, yet also act as discrete particles when measured. Louis de Broglie proposed that all matter has wave-like properties, with a wavelength inversely proportional to its momentum.", "https://cdn.mos.cms.futurecdn.net/gyuT23ZwvfNoevmxW6XMte.jpg"),
    QuantumChapter("Heisenberg's Uncertainty Principle", "Exploring the limits of simultaneously knowing certain pairs of physical properties, like position and momentum.","Werner Heisenberg's uncertainty principle states that it's impossible to precisely measure both the position and momentum of a particle at the same time. The more accurately one property is known, the less accurately the other can be determined. This principle arises from the wave-like nature of particles and has profound implications for our understanding of the quantum world.", "https://kaiserscience.wordpress.com/wp-content/uploads/2020/12/heisenberg-uncertainty-principle.jpg"),
    QuantumChapter("Quantum Superposition", "The concept that particles can exist in multiple states simultaneously until measured.", "Quantum superposition refers to a particle's ability to be in multiple states at once. A classic illustration is Schrödinger's cat thought experiment, where a cat in a sealed box is simultaneously alive and dead until observed. This principle is fundamental to quantum computing, where qubits can represent both 0 and 1 simultaneously, enabling complex computations.","https://nickyoder.com/content/images/2023/05/Title-Quantum-2.jpg"),
    QuantumChapter("Quantum Entanglement", "Understanding how particles can become interconnected, with the state of one instantly influencing the other, regardless of distance.", "Quantum entanglement is a phenomenon where two or more particles become linked, such that the state of one directly affects the state of the other, no matter how far apart they are. This \"spooky action at a distance,\" as Einstein called it, challenges classical notions of locality and has applications in quantum communication and computing.","https://miro.medium.com/v2/resize:fit:1400/1*kg4VGbafmoithj4RZJnX7g.jpeg"),
    QuantumChapter("Quantum Tunneling", "Explaining how particles can pass through energy barriers that they classically shouldn't be able to.","Quantum tunneling is a process where particles move through a barrier that would be insurmountable according to classical physics. This occurs because of the probabilistic nature of quantum mechanics, allowing particles to \"tunnel\" through barriers. Quantum tunneling is essential in phenomena like nuclear fusion in stars and the operation of tunnel diodes.\n" +
            "\n", "https://cdn1.byjus.com/wp-content/uploads/2022/05/quantum-tunnelling.png"),
    QuantumChapter("Applications of Quantum Physics", "Exploring real-world technologies and phenomena that rely on quantum mechanics.", "Quantum physics underpins many modern technologies, including semiconductors, lasers, and magnetic resonance imaging (MRI). Quantum computing leverages principles like superposition and entanglement to perform complex calculations more efficiently than classical computers. Quantum cryptography offers secure communication methods based on quantum principles.","https://media.geeksforgeeks.org/wp-content/uploads/20240510183420/Applications-of-Quantum-Mechanics.png")
)
